version: "3.1"
services:
  adminer:
    image: adminer
    container_name: local-adminer
    restart: always
    ports:
      - "8080:8080"

  db:
    image: mysql:8
    container_name: local-db
    environment:
      MYSQL_ROOT_PASSWORD: secret_password
    ports:
      - "3306:3306"
    volumes:
      - ./_mysql-data:/var/lib/mysql